---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rhwebsco/rumahsakit.rhwebs.com
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "Deployment frontend tersinkronisasi ke rumahsakit.rhwebs.com!" > deploy.log
